spring:
  application:
    name: configuration-service
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8889/eureka}
  instance:
    prefer-ip-address: true